apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::911075010171:role/team6-eks-cluster-node-group-iam-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::911075010171:role/Team6CodeBuildGenericRole
      username: codebuild
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::911075010171:user/sulabh
      username: sulabh
      groups:
        - system:masters
    - userarn: arn:aws:iam::911075010171:user/vikram
      username: vikram
      groups:
        - system:masters
    - userarn: arn:aws:iam::911075010171:user/pankaj
      username: pankaj
      groups:
        - system:masters
    - userarn: arn:aws:iam::911075010171:user/chirag
      username: chirag
      groups:
        - system:masters
    - userarn: arn:aws:iam::911075010171:user/sanjeev
      username: sanjeev
      groups:
        - system:masters
